#
# [ Server Configuration Attributes ]
#
server:
 port: 9010
 contextPath: /api/statistic

#
# [ Spring Database Configuration]
#
spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      port: 27017
      host: localhost
      repositories:
        enabled: true
      reactive-repositories:
        enabled: true
      database: omnie-commerce-statistic
      grid-fs-database: omnie-commerce-fs

#
# [ Spring Email Configuration]
#

  mail:
    host: smtp.gmail.com
    port: 587
    username: omniehp2@gmail.com
    password: omniuser2hp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#
# [ Security Configuration Attributes ]
#
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: web-client
      clientSecret: secret
      accessTokenUri: http://localhost:9005/omnie-security/oauth/check_token
      userAuthorizationUri: http://localhost:9005/omnie-security/oauth/authorize
    resource:
      filter-order: 3
      jwt:
        keyUri: http://localhost:9005/omnie-security/oauth/token_key

#
# [ Logging Configuration Attributes ]
#

logging:
  level:
#    root: info
    com.omniesoft: debug
    org.springframework: info
    org.springframework.security: debug
    org.springframework.cache: debug
    org.hibernate: info
    jdbc: info
    org.apache: info
    jdbc.audit: warn
    jdbc.sqlonly: warn
    jdbc.resultset: warn
    jdbc.sqltiming: warn

---
###
### Profile: dev
###
spring:
    profiles: dev
    datasource:
      url: jdbc:postgresql://db:5432/omnie_commerce
    data:
      mongodb:
       port: 27017
       host: 192.168.65.1

#
# [ Security Configuration Attributes ]
#
security:
  oauth2:
    client:
      clientId: web-client
      clientSecret: secret
      accessTokenUri: http://omnie-security:9005/omnie-security/oauth/check_token
      userAuthorizationUri: http://omnie-security:9005/omnie-security/oauth/authorize
    resource:
      filter-order: 3
      jwt:
        keyUri: http://omnie-security:9005/omnie-security/oauth/token_key


#
# [ Logging Configuration Attributes ]
#

logging:
  config: classpath:logger-to-file.xml